import { create } from 'zustand';
import type { BuilderState, ChartMode, ParsedDataset, SeriesMapping, ChartPreset } from '../types';

interface BuilderStore extends BuilderState {
  setMode: (mode: ChartMode) => void;
  setDataset: (dataset: ParsedDataset | undefined) => void;
  setMapping: (mapping: SeriesMapping) => void;
  setPreset: (preset: ChartPreset) => void;
  setThemeId: (themeId: string) => void;
  setGeneratedOptions: (options: Record<string, unknown>) => void;
  setChartDimensions: (dimensions: { width: number; height: number }) => void;
  setTitle: (title: string) => void;
  setSubtitle: (subtitle: string) => void;
  setSource: (source: string) => void;
  // Advanced settings setters
  setTitleAlign: (align: 'left' | 'center' | 'right') => void;
  setSubtitleAlign: (align: 'left' | 'center' | 'right') => void;
  setTitleUseHTML: (useHTML: boolean) => void;
  setShowCaption: (show: boolean) => void;
  setCaptionText: (text: string) => void;
  setBackgroundColor: (color: string) => void;
  setBorderRadius: (radius: number) => void;
  setSpacingPreset: (preset: 'tight' | 'normal' | 'spacious') => void;
  setInvertedChart: (inverted: boolean) => void;
  setPolar: (polar: boolean) => void;
  setZoomType: (type: 'none' | 'x' | 'y' | 'xy') => void;
  setScrollablePlotArea: (scrollable: boolean) => void;
  setShowCredits: (show: boolean) => void;
  setXAxisTitle: (title: string) => void;
  setXAxisType: (type: 'category' | 'linear' | 'datetime' | 'logarithmic') => void;
  setXAxisLabelRotation: (rotation: number) => void;
  setXAxisLabelStep: (step: number) => void;
  setXAxisMin: (min: number) => void;
  setXAxisMax: (max: number) => void;
  setXAxisTickInterval: (interval: number) => void;
  setXAxisShowGridlines: (show: boolean) => void;
  setXAxisShowAxisLine: (show: boolean) => void;
  setXAxisReverse: (reverse: boolean) => void;
  setXAxisStartOnTick: (start: boolean) => void;
  setXAxisEndOnTick: (end: boolean) => void;
  setYAxisTitle: (title: string) => void;
  setYAxisSecondaryEnabled: (enabled: boolean) => void;
  setYAxisSecondaryTitle: (title: string) => void;
  setYAxisMin: (min: number) => void;
  setYAxisMax: (max: number) => void;
  setYAxisSoftMin: (min: number) => void;
  setYAxisSoftMax: (max: number) => void;
  setYAxisTickInterval: (interval: number) => void;
  setYAxisOpposite: (opposite: boolean) => void;
  setYAxisShowGridlines: (show: boolean) => void;
  setYAxisGridlineStyle: (style: 'solid' | 'dashed' | 'dotted') => void;
  setYAxisAllowDecimals: (allow: boolean) => void;
  setYAxisValuePrefix: (prefix: string) => void;
  setYAxisValueSuffix: (suffix: string) => void;
  setYAxisNumberFormat: (format: 'plain' | 'currency' | 'percent' | 'thousands' | 'millions' | 'billions') => void;
  setSeriesStacking: (stacking: 'none' | 'normal' | 'percent') => void;
  setSeriesLineWidth: (width: number) => void;
  setSeriesMarkerEnabled: (enabled: boolean) => void;
  setSeriesMarkerSize: (size: number) => void;
  setSeriesDashStyle: (style: 'Solid' | 'ShortDash' | 'Dot' | 'Dash' | 'LongDash') => void;
  setSeriesFillOpacity: (opacity: number) => void;
  setSeriesBorderWidth: (width: number) => void;
  setSeriesPointPadding: (padding: number) => void;
  setSeriesGroupPadding: (padding: number) => void;
  setSeriesConnectNulls: (connect: boolean) => void;
  setSeriesAnimation: (animation: boolean) => void;
  setSeriesAnimationDuration: (duration: number) => void;
  setSeriesShowDataLabels: (show: boolean) => void;
  setSeriesShowInLegend: (show: boolean) => void;
  setLegendShow: (show: boolean) => void;
  setLegendPosition: (position: 'top' | 'right' | 'bottom' | 'left') => void;
  setLegendHorizontalAlign: (align: 'left' | 'center' | 'right') => void;
  setLegendVerticalAlign: (align: 'top' | 'middle' | 'bottom') => void;
  setLegendLayout: (layout: 'horizontal' | 'vertical') => void;
  setLegendFloating: (floating: boolean) => void;
  setLegendBackgroundColor: (color: string) => void;
  setLegendBorder: (border: boolean) => void;
  setLegendItemFontSize: (size: string) => void;
  setTooltipEnabled: (enabled: boolean) => void;
  setTooltipShared: (shared: boolean) => void;
  setTooltipSplit: (split: boolean) => void;
  setTooltipUseHTML: (useHTML: boolean) => void;
  setTooltipValueDecimals: (decimals: number) => void;
  setTooltipValuePrefix: (prefix: string) => void;
  setTooltipValueSuffix: (suffix: string) => void;
  setTooltipDateFormat: (format: 'auto' | 'MMM YYYY' | 'MMM D, YYYY' | 'YYYY-MM-DD' | 'custom') => void;
  setTooltipTemplateMode: (mode: 'default' | 'compact' | 'detailed' | 'custom') => void;
  setTooltipBackgroundColor: (color: string) => void;
  setTooltipBorderRadius: (radius: number) => void;
  setDataLabelsEnabled: (enabled: boolean) => void;
  setDataLabelPosition: (position: 'auto' | 'inside' | 'outside' | 'above') => void;
  setDataLabelFormat: (format: 'value' | 'percent' | 'category-value' | 'custom') => void;
  setAxisLabelFontSize: (size: string) => void;
  setAxisLabelColor: (color: string) => void;
  setLabelOverflow: (overflow: 'wrap' | 'truncate' | 'rotate') => void;
  setRangeSelectorEnabled: (enabled: boolean) => void;
  setRangeSelectorButtons: (buttons: ('1m' | '3m' | '6m' | 'ytd' | '1y' | 'all')[]) => void;
  clearDataset: () => void;
  reset: () => void;
}

const initialState: BuilderState = {
  mode: 'standard',
  mapping: {},
  chartDimensions: { width: 800, height: 800 },
  preset: 'line',
  seriesMarkerEnabled: false,
};

export const useBuilderStore = create<BuilderStore>((set) => ({
  ...initialState,

  setMode: (mode) => set({ mode }),
  setDataset: (dataset) => set({ dataset }),
  setMapping: (mapping) => set({ mapping }),
  setPreset: (preset) => set({ preset }),
  setThemeId: (themeId) => set({ themeId }),
  setGeneratedOptions: (generatedOptions) => set({ generatedOptions }),
  setChartDimensions: (chartDimensions) => set({ chartDimensions }),
  setTitle: (title) => set({ title }),
  setSubtitle: (subtitle) => set({ subtitle }),
  setSource: (source) => set({ source }),
  // Advanced settings implementations
  setTitleAlign: (titleAlign) => set({ titleAlign }),
  setSubtitleAlign: (subtitleAlign) => set({ subtitleAlign }),
  setTitleUseHTML: (titleUseHTML) => set({ titleUseHTML }),
  setShowCaption: (showCaption) => set({ showCaption }),
  setCaptionText: (captionText) => set({ captionText }),
  setBackgroundColor: (backgroundColor) => set({ backgroundColor }),
  setBorderRadius: (borderRadius) => set({ borderRadius }),
  setSpacingPreset: (spacingPreset) => set({ spacingPreset }),
  setInvertedChart: (invertedChart) => set({ invertedChart }),
  setPolar: (polar) => set({ polar }),
  setZoomType: (zoomType) => set({ zoomType }),
  setScrollablePlotArea: (scrollablePlotArea) => set({ scrollablePlotArea }),
  setShowCredits: (showCredits) => set({ showCredits }),
  setXAxisTitle: (xAxisTitle) => set({ xAxisTitle }),
  setXAxisType: (xAxisType) => set({ xAxisType }),
  setXAxisLabelRotation: (xAxisLabelRotation) => set({ xAxisLabelRotation }),
  setXAxisLabelStep: (xAxisLabelStep) => set({ xAxisLabelStep }),
  setXAxisMin: (xAxisMin) => set({ xAxisMin }),
  setXAxisMax: (xAxisMax) => set({ xAxisMax }),
  setXAxisTickInterval: (xAxisTickInterval) => set({ xAxisTickInterval }),
  setXAxisShowGridlines: (xAxisShowGridlines) => set({ xAxisShowGridlines }),
  setXAxisShowAxisLine: (xAxisShowAxisLine) => set({ xAxisShowAxisLine }),
  setXAxisReverse: (xAxisReverse) => set({ xAxisReverse }),
  setXAxisStartOnTick: (xAxisStartOnTick) => set({ xAxisStartOnTick }),
  setXAxisEndOnTick: (xAxisEndOnTick) => set({ xAxisEndOnTick }),
  setYAxisTitle: (yAxisTitle) => set({ yAxisTitle }),
  setYAxisSecondaryEnabled: (yAxisSecondaryEnabled) => set({ yAxisSecondaryEnabled }),
  setYAxisSecondaryTitle: (yAxisSecondaryTitle) => set({ yAxisSecondaryTitle }),
  setYAxisMin: (yAxisMin) => set({ yAxisMin }),
  setYAxisMax: (yAxisMax) => set({ yAxisMax }),
  setYAxisSoftMin: (yAxisSoftMin) => set({ yAxisSoftMin }),
  setYAxisSoftMax: (yAxisSoftMax) => set({ yAxisSoftMax }),
  setYAxisTickInterval: (yAxisTickInterval) => set({ yAxisTickInterval }),
  setYAxisOpposite: (yAxisOpposite) => set({ yAxisOpposite }),
  setYAxisShowGridlines: (yAxisShowGridlines) => set({ yAxisShowGridlines }),
  setYAxisGridlineStyle: (yAxisGridlineStyle) => set({ yAxisGridlineStyle }),
  setYAxisAllowDecimals: (yAxisAllowDecimals) => set({ yAxisAllowDecimals }),
  setYAxisValuePrefix: (yAxisValuePrefix) => set({ yAxisValuePrefix }),
  setYAxisValueSuffix: (yAxisValueSuffix) => set({ yAxisValueSuffix }),
  setYAxisNumberFormat: (yAxisNumberFormat) => set({ yAxisNumberFormat }),
  setSeriesStacking: (seriesStacking) => set({ seriesStacking }),
  setSeriesLineWidth: (seriesLineWidth) => set({ seriesLineWidth }),
  setSeriesMarkerEnabled: (seriesMarkerEnabled) => set({ seriesMarkerEnabled }),
  setSeriesMarkerSize: (seriesMarkerSize) => set({ seriesMarkerSize }),
  setSeriesDashStyle: (seriesDashStyle) => set({ seriesDashStyle }),
  setSeriesFillOpacity: (seriesFillOpacity) => set({ seriesFillOpacity }),
  setSeriesBorderWidth: (seriesBorderWidth) => set({ seriesBorderWidth }),
  setSeriesPointPadding: (seriesPointPadding) => set({ seriesPointPadding }),
  setSeriesGroupPadding: (seriesGroupPadding) => set({ seriesGroupPadding }),
  setSeriesConnectNulls: (seriesConnectNulls) => set({ seriesConnectNulls }),
  setSeriesAnimation: (seriesAnimation) => set({ seriesAnimation }),
  setSeriesAnimationDuration: (seriesAnimationDuration) => set({ seriesAnimationDuration }),
  setSeriesShowDataLabels: (seriesShowDataLabels) => set({ seriesShowDataLabels }),
  setSeriesShowInLegend: (seriesShowInLegend) => set({ seriesShowInLegend }),
  setLegendShow: (legendShow) => set({ legendShow }),
  setLegendPosition: (legendPosition) => set({ legendPosition }),
  setLegendHorizontalAlign: (legendHorizontalAlign) => set({ legendHorizontalAlign }),
  setLegendVerticalAlign: (legendVerticalAlign) => set({ legendVerticalAlign }),
  setLegendLayout: (legendLayout) => set({ legendLayout }),
  setLegendFloating: (legendFloating) => set({ legendFloating }),
  setLegendBackgroundColor: (legendBackgroundColor) => set({ legendBackgroundColor }),
  setLegendBorder: (legendBorder) => set({ legendBorder }),
  setLegendItemFontSize: (legendItemFontSize) => set({ legendItemFontSize }),
  setTooltipEnabled: (tooltipEnabled) => set({ tooltipEnabled }),
  setTooltipShared: (tooltipShared) => set({ tooltipShared }),
  setTooltipSplit: (tooltipSplit) => set({ tooltipSplit }),
  setTooltipUseHTML: (tooltipUseHTML) => set({ tooltipUseHTML }),
  setTooltipValueDecimals: (tooltipValueDecimals) => set({ tooltipValueDecimals }),
  setTooltipValuePrefix: (tooltipValuePrefix) => set({ tooltipValuePrefix }),
  setTooltipValueSuffix: (tooltipValueSuffix) => set({ tooltipValueSuffix }),
  setTooltipDateFormat: (tooltipDateFormat) => set({ tooltipDateFormat }),
  setTooltipTemplateMode: (tooltipTemplateMode) => set({ tooltipTemplateMode }),
  setTooltipBackgroundColor: (tooltipBackgroundColor) => set({ tooltipBackgroundColor }),
  setTooltipBorderRadius: (tooltipBorderRadius) => set({ tooltipBorderRadius }),
  setDataLabelsEnabled: (dataLabelsEnabled) => set({ dataLabelsEnabled }),
  setDataLabelPosition: (dataLabelPosition) => set({ dataLabelPosition }),
  setDataLabelFormat: (dataLabelFormat) => set({ dataLabelFormat }),
  setAxisLabelFontSize: (axisLabelFontSize) => set({ axisLabelFontSize }),
  setAxisLabelColor: (axisLabelColor) => set({ axisLabelColor }),
  setLabelOverflow: (labelOverflow) => set({ labelOverflow }),
  setRangeSelectorEnabled: (rangeSelectorEnabled) => set({ rangeSelectorEnabled }),
  setRangeSelectorButtons: (rangeSelectorButtons) => set({ rangeSelectorButtons }),
  clearDataset: () => set({ dataset: undefined, mapping: {} }),
  reset: () => set(initialState),
}));
